from pathlib import Path


def get_dotenv_values(file_path: str) -> dict:
    ret = {}
    with Path(file_path).open("r") as fp:
        dotenv = fp.read().split("\n")[1:]
        dotenv = list(filter(lambda x: x, dotenv))
    for de in dotenv:
        k, v = de.split("=")
        ret.update({k:v})
    return ret

def save_dotenv_values(file_path: str, values: dict) -> None:
    with Path(file_path).open("w") as fp:
        fp.write("# Generated By SDK")
        for k, v in values.items():
            fp.write(f"\n{k}={v}")
